CREATE TABLE CLIENTE(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    nome VARCHAR(80) NOT NULL,
    email VARCHAR(120),
    telefone VARCHAR(12),
    UNIQUE (id)
)
